BEGIN TRANSACTION;
CREATE TABLE `SleepTable` (
	`_id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`duration`	REAL NOT NULL,
	`date`	TEXT NOT NULL,
	`quality`	INTEGER
);
CREATE TABLE `AttentionTable` (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`time`	REAL,
	`date`	TEXT NOT NULL,
	`score`	INTEGER NOT NULL
);
COMMIT;
